layout_spectrum: 0.0939882
color:
  saturation: 0.5712708
  brandStrength: 0.6746167
  lightness: 0.5770609
  rhythmicContrast: 0.7128436
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
typography_spectrum: 0.7955292
name: Golfers worldwide
