color:
  saturation: 0.6666667
  brandStrength: 1
  rhythmicContrast: 0.7007169
  brandColors:
    - '#FFFFFF'
    - '#89A341'
    - '#D5D2C6'
    - '#747056'
    - '#B0AE9B'
  lightness: 0.6845878
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.9982079
typography_spectrum: 0.1774193
name: Golfersworldwide
