layout_spectrum: 0.9982079
color:
  saturation: 0.6666667
  brandStrength: 1
  lightness: 0.6845878
  brandColors:
    - '#FFFFFF'
    - '#89A341'
    - '#D5D2C6'
    - '#747056'
    - '#B0AE9B'
  rhythmicContrast: 0.7007169
typography_spectrum: 0.7955292
name: Golfers worldwide
